<a href="https://colab.research.google.com/github/Nimalnix/AIML/blob/main/Machine_Learning_With_Python_Save_And_Load_Trained_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install pandas numpy scikit-learn matplotlib

In [3]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [4]:
from google.colab import files

uploaded = files.upload()

# Read the uploaded file
import io
df = pd.read_excel(io.BytesIO(uploaded['Book1.xlsx']))
print(df)

Saving Book1.xlsx to Book1.xlsx
   area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  752000


In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [6]:
model.coef_

array([152.43150685])

In [11]:
model.intercept_

131424.65753424645

In [12]:
model.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([893582.19178082])

Save Model To a File Using Python Pickle

In [13]:
import pickle
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

Load Saved Model

In [14]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [15]:
mp.coef_

array([152.43150685])

In [16]:
mp.intercept_

131424.65753424645

In [17]:
mp.predict([[5000]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([893582.19178082])